import { spawn } from 'node:child_process'
import { once } from 'node:events'
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { homedir } from 'node:os'
import { join } from 'node:path'
import {
  PACKAGED_NODE_RECIPES,
  PACKAGED_SKILL_AGENTS,
  type NodeRuntimeRecipe,
} from '../catalog/index.js'
import {
  normalizeCatalog,
  parseGlobalConfiguration,
  type GlobalConfiguration,
} from '../configuration/index.js'
import { devboxPaths, InterruptedError } from '../project/index.js'
import { failure, success, type Result } from '../result.js'
import { withStateLocks } from '../state-lock/index.js'
import { WORKSPACE_IMAGE } from './image.js'

export { WORKSPACE_IMAGE } from './image.js'

export interface DockerBuildInvocation {
  readonly context: string
  readonly image: string
}

export interface BuildWorkspaceInput {
  readonly devboxHome?: string
  readonly signal?: AbortSignal
  readonly executeDockerBuild?: (
    invocation: DockerBuildInvocation,
    signal?: AbortSignal,
  ) => Promise<Result<void>>
}

export interface WorkspaceBuild {
  readonly image: string
}

export type BuildWorkspaceResult = Result<WorkspaceBuild>

export async function buildWorkspace(
  input: BuildWorkspaceInput = {},
): Promise<BuildWorkspaceResult> {
  return withStateLocks(
    {
      devboxHome: input.devboxHome ?? join(homedir(), '.devbox'),
      global: true,
      projectRoots: [],
      signal: input.signal,
    },
    () => buildWorkspaceUnlocked(input),
  )
}

async function buildWorkspaceUnlocked(input: BuildWorkspaceInput): Promise<BuildWorkspaceResult> {
  if (input.signal?.aborted) {
    throw new InterruptedError()
  }

  const catalogCheck = normalizeCatalog()
  if (!catalogCheck.ok) {
    return catalogCheck
  }

  const paths = devboxPaths(input.devboxHome)
  let globalSource: string
  try {
    globalSource = await readFile(paths.globalConfiguration, 'utf8')
  } catch {
    return failure({
      kind: 'operational',
      code: 'global-configuration-missing',
      observed: 'Global configuration is required before building the Workspace image.',
      nextAction: 'Run devbox config to commit Global configuration before devbox build.',
    })
  }

  const parsedGlobal = parseGlobalConfiguration(globalSource, catalogCheck.value)
  if (!parsedGlobal.ok) {
    return parsedGlobal
  }
  const globalConfiguration: GlobalConfiguration = parsedGlobal.value

  const dockerfile = renderBuildDockerfile({
    nodeRuntimes: globalConfiguration.node.map(releaseLine => PACKAGED_NODE_RECIPES[releaseLine]),
    buildNodeRuntime: buildNodeRuntimeRecipe(globalConfiguration),
    skillAgents: globalConfiguration.agent.filter(agent =>
      (PACKAGED_SKILL_AGENTS as readonly string[]).includes(agent),
    ),
  })

  await rm(paths.buildContext, { recursive: true, force: true })
  await mkdir(paths.buildContext, { recursive: true })
  await writeFile(join(paths.buildContext, 'Dockerfile'), dockerfile)
  await writeFile(
    join(paths.buildContext, '.dockerignore'),
    '# Machine-owned Workspace build context\n*\n!Dockerfile\n',
  )

  if (input.signal?.aborted) {
    throw new InterruptedError()
  }

  const execute = input.executeDockerBuild ?? runDockerBuild
  const buildResult = await execute(
    { context: paths.buildContext, image: WORKSPACE_IMAGE },
    input.signal,
  )
  if (!buildResult.ok) {
    return buildResult
  }

  return success({ image: WORKSPACE_IMAGE })
}

function buildNodeRuntimeRecipe(
  globalConfiguration: GlobalConfiguration,
): NodeRuntimeRecipe | undefined {
  let buildNodeRuntime: NodeRuntimeRecipe | undefined
  for (const releaseLine of globalConfiguration.node) {
    const recipe = PACKAGED_NODE_RECIPES[releaseLine]
    if (
      buildNodeRuntime === undefined ||
      Number.parseFloat(releaseLine) > Number.parseFloat(buildNodeRuntime.releaseLine)
    ) {
      buildNodeRuntime = recipe
    }
  }
  return buildNodeRuntime
}

function renderBuildDockerfile(input: {
  readonly nodeRuntimes: readonly NodeRuntimeRecipe[]
  readonly buildNodeRuntime: NodeRuntimeRecipe | undefined
  readonly skillAgents: readonly string[]
}): string {
  const lines: string[] = [
    '# Generated by devbox build. Machine-owned Workspace build context.',
    'FROM ubuntu:24.04',
    '',
    'ENV DEBIAN_FRONTEND=noninteractive',
    'ENV TZ=UTC',
    'ENV LANG=C.UTF-8',
    '',
    'RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone',
    '',
    '# Install the Base profile packages and build tools',
    'RUN set -eux \\',
    '    && apt-get update && apt-get upgrade -y \\',
    '    && apt-get install -y --no-install-recommends \\',
    '      ca-certificates curl wget git supervisor openssh-client \\',
    '      zip unzip jq less vim ripgrep fd-find procps lsof iproute2 \\',
    '      dnsutils netcat-openbsd rsync tree tzdata bubblewrap \\',
    '      build-essential python3 python-is-python3 pkg-config \\',
    '      gnupg dirmngr xz-utils pulseaudio-utils sudo gosu \\',
    '    && apt-get -y autoremove \\',
    '    && apt-get clean \\',
    '    && rm -rf /var/lib/apt/lists/*',
    '',
    '# Create the devbox user and group',
    'RUN userdel -r ubuntu \\',
    '    && groupadd -f -g 1000 devbox \\',
    '    && useradd -m -s /bin/bash -N -g 1000 -u 1000 devbox \\',
    '    && echo "devbox ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/devbox \\',
    '    && chmod 0440 /etc/sudoers.d/devbox',
    '',
  ]

  for (const recipe of input.nodeRuntimes) {
    lines.push(...renderNodeRuntimeStage(recipe))
  }

  lines.push('WORKDIR /workspace', 'USER devbox', '')

  if (input.buildNodeRuntime !== undefined) {
    lines.push(
      '# Configure pnpm for the non-root Sandbox user',
      'RUN mkdir -p /home/devbox/.config/pnpm /home/devbox/.pnpm-store \\',
      "    && printf 'storeDir: /home/devbox/.pnpm-store\\n' > /home/devbox/.config/pnpm/config.yaml \\",
      '    && chown devbox:devbox /home/devbox/.config/pnpm/config.yaml',
      '',
    )

    for (const agent of input.skillAgents) {
      lines.push(
        '# Install Agent Skills',
        'RUN set -eux \\',
        '    && mkdir -p /home/devbox/.agents/skills \\',
        `    && export PATH="${input.buildNodeRuntime.runtimeRoot}/bin:$PATH" \\`,
        `    && npx -y skills add ycs77/skills -g -a ${agent} -s '*' -y`,
        '',
      )
    }
  }

  lines.push('USER root', '')

  return `${lines.join('\n')}\n`
}

function renderNodeRuntimeStage(recipe: NodeRuntimeRecipe): string[] {
  const keys = recipe.trustedReleaseKeys.map(key => `      ${key}`).join(' \\\n')

  return [
    `# Install Node.js ${recipe.releaseLine}`,
    'RUN ARCH= OPENSSL_ARCH= && dpkgArch="$(dpkg --print-architecture)" \\',
    '    && case "${dpkgArch##*-}" in \\',
    "      amd64) ARCH='x64' OPENSSL_ARCH='linux-x86_64';; \\",
    "      ppc64el) ARCH='ppc64le' OPENSSL_ARCH='linux-ppc64le';; \\",
    "      s390x) ARCH='s390x' OPENSSL_ARCH='linux*-s390x';; \\",
    "      arm64) ARCH='arm64' OPENSSL_ARCH='linux-aarch64';; \\",
    '      *) echo "unsupported architecture"; exit 1 ;; \\',
    '    esac \\',
    '    && set -eux \\',
    `    && NODE_RUNTIME_VERSION=${recipe.version} \\`,
    `    && NODE_RUNTIME_ROOT=${recipe.runtimeRoot} \\`,
    `    && NODE_ARCHIVE_URL="https://nodejs.org/dist/v${recipe.version}/node-v\${NODE_RUNTIME_VERSION}-linux-\${ARCH}.tar.xz" \\`,
    `    && NODE_CHECKSUMS_URL="https://nodejs.org/dist/v${recipe.version}/SHASUMS256.txt.asc" \\`,
    '    && mkdir -p "$NODE_RUNTIME_ROOT" /tmp/node-source \\',
    '    && cd /tmp/node-source \\',
    '    && export GNUPGHOME="$(mktemp -d)" \\',
    '    && for key in \\',
    `${keys} \\`,
    '    ; do \\',
    '      { gpg --batch --no-options --keyserver hkps://keys.openpgp.org --recv-keys "$key" && gpg --batch --no-options --fingerprint "$key"; } || \\',
    '      { gpg --batch --no-options --keyserver keyserver.ubuntu.com --recv-keys "$key" && gpg --batch --no-options --fingerprint "$key"; }; \\',
    '    done \\',
    '    && archive="node-v${NODE_RUNTIME_VERSION}-linux-${ARCH}.tar.xz" \\',
    '    && curl -fsSL --retry 3 -o "$archive" "$NODE_ARCHIVE_URL" \\',
    '    && curl -fsSL --retry 3 -o SHASUMS256.txt.asc "$NODE_CHECKSUMS_URL" \\',
    '    && gpg --batch --no-options --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc \\',
    '    && gpgconf --kill all \\',
    '    && rm -rf "$GNUPGHOME" \\',
    '    && awk -v archive="$archive" \\',
    "      '$2 == archive { print; found = 1; exit } END { if (!found) exit 1 }' \\",
    '      SHASUMS256.txt > "$archive.sha256" \\',
    '    && sha256sum --check "$archive.sha256" \\',
    '    && tar --extract --xz --file "$archive" --directory "$NODE_RUNTIME_ROOT" \\',
    '      --strip-components=1 --no-same-owner \\',
    '    && rm "$archive" SHASUMS256.txt.asc SHASUMS256.txt "$archive.sha256" \\',
    '    && find "$NODE_RUNTIME_ROOT/include/node/openssl/archs" -mindepth 1 -maxdepth 1 ! -name "$OPENSSL_ARCH" -exec rm -rf {} \\; \\',
    '    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \\',
    '    && export PATH="$NODE_RUNTIME_ROOT/bin:$PATH" \\',
    '    && npm install -g npm \\',
    '    && npm uninstall -g corepack \\',
    '    && npm install -g yarn pnpm @antfu/ni \\',
    '    && "$NODE_RUNTIME_ROOT/bin/node" --version \\',
    '    && "$NODE_RUNTIME_ROOT/bin/npm" --version \\',
    '    && rm -rf /tmp/node-source',
    '',
  ]
}

async function runDockerBuild(
  invocation: DockerBuildInvocation,
  signal?: AbortSignal,
): Promise<Result<void>> {
  const build = spawn(
    'docker',
    [
      'build',
      '--tag',
      invocation.image,
      '--file',
      join(invocation.context, 'Dockerfile'),
      invocation.context,
    ],
    { stdio: 'inherit' },
  )
  const interrupt = () => build.kill('SIGINT')
  signal?.addEventListener('abort', interrupt, { once: true })

  let spawnFailed = false
  build.on('error', () => {
    spawnFailed = true
  })
  const [exitCode] = (await once(build, 'close')) as [number | null]
  signal?.removeEventListener('abort', interrupt)

  if (signal?.aborted) {
    throw new InterruptedError()
  }
  if (spawnFailed || exitCode !== 0) {
    return failure({
      kind: 'operational',
      code: 'docker-build-failed',
      observed: `Docker failed to build ${invocation.image}.`,
      nextAction: 'Inspect the Docker output above; the prior Workspace image is unchanged.',
    })
  }
  return success(undefined)
}
